name: Lint

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - master

jobs:
    lintDebug:
        name: Lint Debug
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Run Lint
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: lint
